=== MilaniFrancesco7/Scuola/Sistemi/Programmi/RubricaXML/Rubrica/rubrica.dtd
<!DOCTYPE rubrica		
[
<!ELEMENT rubrica (name,middlename,surname,birth,phone,city,email)> 
<!ELEMENT name (#PCDATA)>						
<!ELEMENT middlename (#PCDATA)>					
<!ELEMENT surname (#PCDATA)>					
<!ELEMENT birth (#PCDATA)>					
<!ELEMENT phone (#PCDATA)>						
<!ELEMENT city (#PCDATA)>						
<!ELEMENT email (#PCDATA)>						
]>

=== MilaniFrancesco7/Scuola/Sistemi/Programmi/RubricaXML/Rubrica/rubrica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rubrica SYSTEM "rubrica.dtd">
<rubrica>
	<contact> 	
		<name>Francesco</name>
		<middlename>Luigi</middlename>
		<surname>Milani</surname>
		<birth y="2000" m="09" d="08" />
		<phone>3492121901</phone>
		<city>Rossano Veneto</city>
		<email>milaniwork@gmail.com</email>
	</contact>
	
	<contact>
		<name>Giacomino</name>
		<middlename>Sugar</middlename>
		<surname>Poretti</surname>
		<birth y="1975" m="10" d="19" />
		<phone>3492846289</phone>
		<city>Milano</city>
		<email>sugarporetti@tiscali.it</email>
	</contact>
	
	<contact>
		<name>Cataldo</name>
		<middlename>Dexter</middlename>
		<surname>Baglio</surname>
		<birth y="1973" m="8" d="25" />
		<phone>34956567801</phone>
		<city>Milano</city>
		<email>dexterbaglio@alice.it</email>
	</contact>	
	
	<contact>
		<name>Giovanni</name>
		<middlename>Esagerato</middlename>
		<surname>Storti</surname>
		<birth y="1976" m="2" d="21" />
		<phone>3492278015</phone>
		<city>Milano</city>
		<email>esageratostorti@hotmail.com</email>
	</contact>		
	
</rubrica>
